### ISSUE TITLE
cannot find module `pug`

### ISSUE THREAD

**Issue by andy5995** [whykatherine/agloballanguage#3]
Using `npm install pug` seemed to fix the problem. To have that install automatically, would I just add pug to the deps in package.json?

I received this error in the console:

```
GET /favicon.ico 404 1.369 ms - 1011
Error: Cannot find module 'pug'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at new View (/home/andy/src/etymologee/node_modules/express/lib/view.js:79:30)
    at EventEmitter.render (/home/andy/src/etymologee/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/home/andy/src/etymologee/node_modules/express/lib/response.js:971:7)
    at /home/andy/src/etymologee/app.js:43:7
    at Layer.handle_error (/home/andy/src/etymologee/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/andy/src/etymologee/node_modules/express/lib/router/index.js:315:13)

```

**Comment by kayserifserif** [comment]
Fixed with commit 10530631f139e4bf20b7ae2814e8800fbe9041ec
